name: "Render.com Deploy Action"
description: "Trigger a Render service deploy"
branding:
  icon: activity
  color: black
inputs:
  service-id:
    description: "Your Render service ID"
    required: true
  api-key:
    description: "Your Render API key"
    required: true
  wait-for-success:
    description: "Wait for deployment to succeed"
    required: false
runs:
  using: "node20"
  main: "dist/index.js"
